title: Sam J Griffin
base_url: samjgriffin.com
email: samjgriffin89@gmail.com

meta_title: Sam J Griffin | Engineer & Kid at Heart
description: I'm an engineer. I'm a kid at heart. I enjoy solving complex problems like scalability of applications, and also sledding down sand dunes at 40mph.

google_analytics_id: UA-24433484-1
google_site_verification: cT3CHL7PrHfUex3GIuLkyjnk-deuZyedUYGqJGOKGEc

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - .gitignore
  - README.md