title: Olney Fan
base_url: https://www.olneyfan.com
email: me@olneyfan

meta_title: Olney Fan
description: Welcome to Olney Fan, the site for you and all your friends to enjoy!

google_analytics_id: 
google_site_verification: cT3CHL7PrHfUex3GIuLkyjnk-deuZyedUYGqJGOKGEc

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - .gitignore
  - README.md

issues_repo: samjgriffin89/olneyfan.com